% plotElev
%
% Plots 10 meter DEM of Seattle
%
%	Required variables:
%           x: row of x values generated by loadElev [m]
%           y: row of y values generated by loadElev [m]
%           z: 2D array of elevation values generated by loadElev [m]
%

disp('Plotting elevation data...');
%figure(1);
imagesc(x/1000,y/1000,z'); hold on;
axis equal; axis([min(x) max(x) min(y) max(y)]/1000);
caxis([-10 160]);

contour(x/1000,y/1000,z',[1 1],'w');
xlabel('[km]');
ylabel('[km]');

cb = colorbar; cbt = get(cb,'title');
set(cbt,'string','Elevation [m]');
