function plotFS(x_val,y_val,z_val,FS)

% function []=plotFS(x_val,y_val,z_val,FS)
%
% Plots the factor of safety
%
% Input     x_val: row of x values generated by loadElev [m]
%           y_val: row of y values generated by loadElev [m]
%           z_val: 2D array of elevation values generated by loadElev [m]
%          FS: 2D array of slope values generated by calcFS
%
% Output    None
%

% Make image, axes in kilometers
imagesc(x_val/1000,y_val/1000,FS'); hold on;

% Set the axis properties
axis equal; axis([min(x_val) max(x_val) min(y_val) max(y_val)]/1000);

% Add sea level contour
contour(x_val/1000,y_val/1000,z_val',[1 1],'w');

xlabel('[km]'); ylabel('[km]');

% Make a colorbar
caxis([0 10]);  % set the min,max of the color spectrum
cb = colorbar; 

% Set the title of the colorbar
cbt = get(cb,'title');
set(cbt,'string','FS');
